spring:
  application:
    name: libraryAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

